trigger:
  branches:
    include:
      - master

variables:
  azureServicePrincipal: k8s-cluster

stages:
  # Build
  - template: Templates/Build.yaml
    parameters:
      dockerFile: Dockerfile
      dockerRepository: azureoxford/azureoxford-website
      buildContext: .
      helmChartPath: $(System.DefaultWorkingDirectory)/DevOps/WebChart/

  # Deploy
  - template: Templates/Deploy.yaml
    parameters:
      environment: uat
      tag: $(Build.BuildId)
      name: web
      imageName: azureoxford/azureoxford-website