apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: azureoxford-website
spec:
  replicas: 1
  selector:
    matchLabels:
      ref: web
  template:
    metadata:
      labels:
        ref: web
    spec:
      containers:
      - name: web
        image: azureoxford/azureoxford-website:000
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: azureoxford-website
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    ref: web
